[compiler.solc]
exclude_paths = ["source/node_modules", "source/script", "source/test"]
include_paths = ["source/node_modules"]
remappings = [
    "@openzeppelin/=source/node_modules/@openzeppelin/",
    "solmate/=source/node_modules/solmate/src/",
    "solady/=source/node_modules/solady/src/",
    "forge-std/=source/node_modules/forge-std/src/",
    "ds-test/=source/node_modules/ds-test/src/",
    "src/=source/src/",
]

[compiler.solc.optimizer]
enabled = true
runs = 200

[detectors]
exclude = []
ignore_paths = ["source/test"]
exclude_paths = ["source/node_modules", "source/script"]

[testing]
cmd = "anvil"

[testing.anvil]
cmd_args = "--prune-history 100 --transaction-block-keeper 10 --steps-tracing --silent"

[testing.ganache]
cmd_args = "-k istanbul -q"

[testing.hardhat]
cmd_args = ""

